<?php
/**
 * Title: Cta
 * Slug: shopverse/cta
 * Categories: shopverse
 *
 * @package ShopVerse
 * @since 1.0.0
 */

?>

<?php if (function_exists('wc_booster_load') && class_exists('WooCommerce')) { ?>

<!-- wp:wc-booster/section {"block_id":"wc-booster-section-block-instance-6-09602f91-7b89-483a-b2fa-36dd6ac4e8dd","padding":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","em"],"range":{"min":10,"max":300},"values":{"desktop":[80,0,80,0],"tablet":[15,15,0,15],"mobile":[30,15,30,15]}},"margin":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","em"],"range":{"min":10,"max":300},"values":{"desktop":[null,null,null,null],"tablet":[0,0,0,0],"mobile":[0,0,0,0]}},"containerType":"full-width","containerWidth":{"activeUnit":"px","range":{"min":1,"max":2000},"values":{"desktop":1300,"tablet":1024,"mobile":640},"units":["px"]},"bgImage":{"size":"full","id":5773,"alt":"high-angle-travel-items-arrangement","url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":1013,"width":2560,"sizes":{"thumbnail":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":150,"width":150,"orientation":"landscape"},"medium":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":119,"width":300,"orientation":"landscape"},"large":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":405,"width":1024,"orientation":"landscape"},"full":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":1013,"width":2560,"orientation":"landscape"},"1536x1536":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":608,"width":1536,"orientation":"landscape"},"2048x2048":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":811,"width":2048,"orientation":"landscape"},"woocommerce_thumbnail":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":300,"width":300,"orientation":"landscape"},"woocommerce_single":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":238,"width":600,"orientation":"landscape"},"woocommerce_gallery_thumbnail":{"url":"<?php echo esc_url( get_template_directory_uri() ); ?>/assets/images/cta.jpg","height":100,"width":100,"orientation":"landscape"}}},"bgPosition":"top center","bgAttachment":true,"bgOverlay":"rgba(0, 0, 0, 0.43 )","metadata":{"ignoredHookedBlocks":["wc-booster/wish-list-button","wc-booster/quick-view"]}} -->
<div id="wc-booster-section-block-instance-6-09602f91-7b89-483a-b2fa-36dd6ac4e8dd" class="wp-block-wc-booster-section"><div class="wc-booster-full-width wc-booster-section-wrapper"><div class="wc-booster-section-overlay"></div><div class="wc-booster-section-inner"><!-- wp:wc-booster/section {"block_id":"wc-booster-section-block-instance-7-0a785aed-3487-40f3-b0b7-452fc5a7a5e8","padding":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","em"],"range":{"min":10,"max":300},"values":{"desktop":[0,0,0,0],"tablet":[15,0,15,0],"mobile":[15,0,15,0]}},"containerWidth":{"activeUnit":"px","range":{"min":1,"max":2000},"values":{"desktop":1300,"tablet":720,"mobile":540},"units":["px"]}} -->
<div id="wc-booster-section-block-instance-7-0a785aed-3487-40f3-b0b7-452fc5a7a5e8" class="wp-block-wc-booster-section"><div class="wc-booster-boxed wc-booster-section-wrapper"><div class="wc-booster-section-overlay"></div><div class="wc-booster-section-inner"><!-- wp:wc-booster/call-to-action {"block_id":"wc-booster-cta-block-61a33129-e316-4d94-847d-535ff8eedd6f","bgColor":"","padding":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[90,30,90,30],"tablet":[70,30,70,30],"mobile":[50,20,50,20]}},"subDescriptionMargin":{"activeUnit":"px","isLinkActive":false,"properties":["top","right","bottom","left"],"responsiveViews":["desktop","tablet","mobile"],"units":["px","rem"],"values":{"desktop":[30,0,30,0],"tablet":[15,30,15,0],"mobile":[15,30,15,0]}},"heading":"Shop the Latest Trends Now!","subDescription":"Aliquam netus nisi velit tellus suspendisse conubia venenatis elit amet porttitor bibendum vivamus erat praesent pretium facilisis Fringilla turpis nisi sodales in  ","subDescriptionColor":"#ffffff","alignment":"center","headingColor":"#ffffff","opacity":0,"contentWidth":{"activeUnit":"%","range":{"min":1,"max":100},"values":{"desktop":70,"tablet":100,"mobile":100},"responsiveViews":["desktop","tablet","mobile"],"units":["%"]},"headingTypo":{"fontFamily":"Jost, sans-serif","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":48,"tablet":32,"mobile":26},"range":{"min":0,"max":100}},"fontWeight":"500","lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1,"tablet":1,"mobile":1}}},"subDescriptionTypo":{"fontFamily":"Jost, sans-serif","fontSize":{"units":["px","em","rem"],"activeUnit":"px","values":{"desktop":18,"tablet":16,"mobile":16}},"fontWeight":400,"lineHeight":{"activeUnit":"","units":[""],"values":{"desktop":1.5,"tablet":1.6,"mobile":1.6},"range":{"min":0,"max":100}}}} -->
<!-- wp:buttons {"lock":{"move":false,"remove":false},"align":"left","layout":{"type":"flex","justifyContent":"center"}} -->
<div class="wp-block-buttons"><!-- wp:button {"backgroundColor":"white","textColor":"primary","lock":{"move":false,"remove":false},"style":{"border":{"radius":"0px"},"elements":{"link":{"color":{"text":"var:preset|color|primary"}}}},"fontFamily":"jost"} -->
<div class="wp-block-button has-jost-font-family"><a class="wp-block-button__link has-primary-color has-white-background-color has-text-color has-background has-link-color wp-element-button" href="#" style="border-radius:0px"><?php echo esc_html__( 'Shop Now', 'shopverse' ); ?></a></div>
<!-- /wp:button --></div>
<!-- /wp:buttons -->
<!-- /wp:wc-booster/call-to-action --></div></div></div>
<!-- /wp:wc-booster/section --></div></div></div>
<!-- /wp:wc-booster/section -->

<?php } ?>